---
- name: Install apt packages 
  become: true
  apt:
    name:
      # essential build tools (gcc, make, etc)
      - build-essential
      - libtool
      - python
      - python3
      - pkg-config
      - flex
      - bison
      - libssl-dev
      - autotools-dev
      - automake

      # Needed for mounting recovery image
      - kpartx

      # Audio / CRAS dependencies
      - acpid
      - libudev-dev
      - libsbc-dev
      - libalsaplayer-dev
      - libiniparser-dev
      - ladspa-sdk
      - libspeex-dev
      - libspeexdsp-dev
      - libasound2-dev

      # Touchpad
      - libgtest-dev
      - libjsoncpp-dev
      - libxi-dev
      - xutils-dev
      - xserver-xorg-dev

      # Video Driver Issues, may need additional troubleshooting. See README
      - firmware-linux-nonfree

    state: latest 

